### ISSUE TITLE
Sonarqube 8.9 LTS Fails to start

### ISSUE THREAD

**Issue by mieliespoor** [42Crunch/sonarqube-plugin-releases#1]
We tried to install this version today on our Sonarqube instance after which Sonarqube failed to start. I will get logs from Sonarqube, although it didn't point us in the way of this plugin, but we got an exit code of 143. Once we removed the plugin again, we got Sonarqube starting and stable again.

**Comment by ak1394** [comment]
Could you confirm which plugin JAR did you use? There are two JARs in the 2.0.1 release ("sonar-42crunch-plugin-2.0.1.jar" and "sonar-42crunch-plugin-2.0.1-compat.jar")? 

Newer versions of SonarQube include YAML language definition which is present in "sonar-42crunch-plugin-2.0.1.jar" which results in a similar failure. I suggest trying with "sonar-42crunch-plugin-2.0.1-compat.jar".

**Comment by mieliespoor** [comment]
Thanks for that. We now installed it using the -compat.jar and it worked. Sonarqube started up this time.
